### ISSUE TITLE
Fonction champ recherche

### ISSUE THREAD

**Issue by TotorBelleville** [blank-project/contacts-manager#10]
- la recherche par mot clé (type nom, adresse, code postal) fonctionne pas si tu rentre pas un nom complet : par ex il trouve pas "hannah" si tu rentres "hanna" est il possible d'envisager une recherche plus souple genre partie de mot ?

**Comment by erwanosouf** [comment]
Pas compatible avec comment c'est géré actuellement, mais je vais changer ça

**Comment by erwanosouf** [comment]
Le champ recherche garde le même comportement mais j'ai ajouté des nouveaux champs
