### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by erwanosouf** [blank-project/contacts-manager#2]
https://www.npmjs.com/package/csv

**Comment by TotorBelleville** [comment]
Assez chaud de pas taper tous nos contacts à la main et de pouvoir importer des contacts en masse puis après étiqueter un par un. Ca peut être limite la priorité numéro 1 si la base de donnée est stable

**Comment by erwanosouf** [comment]
Ouais faudrait le faire avec les colonnes dans l'ordre et qui respecte le format des champs
